---
fileVersion: v1
instanceName: Counter
protoFile: "/grpc-examples/counter/counter.proto"
calls:

- method: demo.Counter/IncrementCount
  scenario:
    name: counter
    requiredState: started
    newState: run2
  response:
    body:
      count: 1
    status: OK

- method: demo.Counter/IncrementCount
  scenario:
    name: counter
    requiredState: run2
    newState: run3
  response:
    body:
      count: 2
    status: OK

- method: demo.Counter/IncrementCount
  scenario:
    name: counter
    requiredState: run3
    newState: started
  response:
    body:
      count: 3
    status: OK

- method: demo.Counter/AccumulateCount
  request:
    stream:
      - count: 1
      - count: 2
      - count: 3
  response:
    body:
      count: 6
    status: OK

- method: demo.Counter/Countdown
  response:
    stream:
      - count: 9
      - count: 8
      - count: 7
      - count: 6
      - count: 5
