---
fileVersion: v1
instanceName: Credentials
protoFile: "/grpc-examples/credentials/greet.proto"

# limit all connections using an IP address white list
channel:
  credentials:
  - type: ip-white-list
    allowedIps:
    - 190.152.*.*    # wildcards are supported
    - 81.214.*.*
    - 192.188.53.0/24  # CIDR notation is supported

# Incoming request matching is done in the order of definition,
# sequentially, from the first one to the last one,
# once match is found, the processing stops
calls: 

# First, we try to match a call to Joe
- method: demo.Greeter/SayHello
  credentials:
  - type: basic-auth
    user: joe
    password: "$RSA2048:OXtEk9wNKCFqe8eSGCKLf3RpjN8TVwA2huVMbR2wvd/C7cv38Ee/vkM38+ldzcJr8vfiNnbsknRI9n0O3/S5STQSt9ikj9SypMoemcjej2vFgLsRgrhhNAT3DkLcx9LI3Rqg10S+dbb3MRoUZBfZak4k4pHKdjHWW9n5qkjnzSsPySJ/J0+LGZ7gq/ibYoFvRIddW2R0E0jQcisT4/u+vcQW8xSRggmVeTBei7weVq1zruteL1+8a0FGS7S/P8FT8fWjf3kiF2BDNkPqmm4zBucP36MqjdYIhs4Yx80QBZj0wIe0G53XTSvYRLxHaAxduA37hWbkNYznmpXsJjmxTw=="
  request:
    body:
      Name:
        matchesWildcard: '*'
  response:
    body:
      Message: Hello Joe!
    status: OK

# Then, we try to match a call to Kelly
- method: demo.Greeter/SayHello
  credentials:
  - type: basic-auth
    user: kelly
    password: do-not-store-me-in-plain-text-use-enrypt-string-feature-instead
  request:
    body:
      Name:
        matchesWildcard: '*'
  response:
    body:
      Message: Hello Kelly!
    status: OK

# And if no match, fall back to NotFound
- method: demo.Greeter/SayHello
  # "request" section is optional and may absent
  #   -  if "request" section is absent 
  #      then any call of the method is matched
  response:
    statusCode: NOT_FOUND
    statusDetails: Name not found