---
fileVersion: v1
instanceName: PostsUrlPath
calls:
- url: /post/{id}
  method: get
  response:
    body:
      id: "{{ path.id }}"
      title: "{{ Faker.Lorem.Sentence }}"
      body: "{{ Faker.Lorem.Text }}"

    status: OK

- url: /post/{id}
  method: put
  response:
    body:
      id: "{{ path.id }}"
      title: "{{ request.body.title }}"
      body: "{{ request.body.body }}"
    status: OK

- url: /post/{id}
  method: delete
  response:
    status: OK
