---
fileVersion: v1
instanceName: PostsUrlPath
calls:
- url: /post/{id}
  method: get
  response:
    body:
      id: "{{ path.id }}"
      title: Blog Post Title
      body: |
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor 
        in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, 
        sunt in culpa qui officia deserunt mollit anim id est laborum

    status: OK

- url: /post/{id}
  method: put
  response:
    body:
      id: "{{ path.id }}"
      title: "{{ request.body.title }}"
      body: "{{ request.body.body }}"
    status: OK

- url: /post/{id}
  method: delete
  response:
    status: OK
